name: ultratherm
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - biopython
  - pyyaml
  - pip
  - pip:
    # NOTE: bioconda viennarna does not work! Use PyPi
    - viennarna>=2.6.4
