name: ultratherm
channels:
 - conda-forge
 - bioconda
dependencies:
 - python=3.9
 - numpy
 - scipy
 - pandas
 - biopython
 - pyyaml
 - pip
 - pip:
  # bioconda viennarna does not work! use PyPi
  - viennarna